### ISSUE TITLE
Visual studio 2017

### ISSUE THREAD

**Issue by corbane** [mattkol/Chromely#39]
Hello, Thank you for this beautiful project!

I followed these steps: https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template
And it works well.

But when I open the project in vs2017 and run the debug.
I have an empty window an the dotnet console open with this message

```
2018-07-04 19:29:25.726 [ERROR] Oops! Something went wrong.     Unable to load DLL 'libcef' or one of its dependencies: Le module spécifié est introuvable. (Exception from HRESULT: 0x8007007E)           at Xilium.CefGlue.Interop.libcef.api_hash(Int32 entry)
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Chromely.CefGlue.Winapi.ChromeHost.CefGlueBrowserHost.OnCreate(CreateWindowPacket& packet)
   at WinApi.Windows.Packetizer.ProcessCreate(WindowMessage& msg, EventedWindowCore window)
   at WinApi.Windows.WindowCore.WindowProc(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
2018-07-04 19:29:25.756 [ERROR] Oops! Something went wrong.     Object reference not set to an instance of an object.
   at Chromely.CefGlue.Winapi.ChromeHost.CefGlueBrowserHost.OnSize(SizePacket& packet)
   at WinApi.Windows.Packetizer.ProcessSize(WindowMessage& msg, EventedWindowCore window)
   at WinApi.Windows.WindowCore.WindowProc(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
2018-07-04 19:29:25.779 [ERROR] Oops! Something went wrong.     Object reference not set to an instance of an object.
   at Chromely.CefGlue.Winapi.ChromeHost.CefGlueBrowserHost.OnSize(SizePacket& packet)
   at WinApi.Windows.Packetizer.ProcessSize(WindowMessage& msg, EventedWindowCore window)
   at WinApi.Windows.WindowCore.WindowProc(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

(I'am on windows 64 and with the last Chromely)

I tested these steps : https://github.com/mattkol/Chromely/wiki/CefGlue-Application-Layout, but with no sucess.

Do you understand more me ?

Thank you !

**Comment by CWolfs** [comment]
I'm not the developer of this project but I'll take a wild guess.

You might be hitting the same issue I had when users of my program couldn't run it. I needed to get them to install (which I then later bundled in) Visual C++ 2013 x64 (as I'm building only for x64).

You might be hitting the same issue? Do you have Visual C++ 2013 or Visual Studio 2013 installed? If not, then try installing Visual C++ 2013 redist on your computer - then see if that works?

https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by mattkol** [comment]
@corbane thanks or the compliment

The only reason I know you will have: _Unable to load DLL 'libcef' or one of its dependencies:_  error is if the CEF binaries are missing or you have the wrong version. Please ensure that the binaries you have are the right versions - as mapped in the table [here]( https://github.com/mattkol/Chromely/wiki/CefGlue-Application-Layout)

If you want to do a quick test without binaries  download you can try the most recent CefGlue version (prelease - v66). This would not require a CEF download by you. It gets the binaries for you the first time you build.

Via Nuget:
**Install-Package Chromely.CefGlue.Winapi -Version 66.0.0-pre01**

**Comment by mattkol** [comment]
@CWolfs I added CefGlue as an option because of the VC++ distributable required for CefSharp.
Thanks for sharing the info.

**Comment by corbane** [comment]
Thank you !

I found the solution but i haven't be cleary:

> I followed these steps: https://github.com/mattkol/Chromely/wiki/dotnet-cli-Starter-Template
And it works well.
> But when I open the project in vs2017 and run the debug.

I would say:

With dotnet run in command line, the application start good, but not if i use VS2017

---

the problem is that the csproj generated by the starter template does not define the output build.
So, by default, VS sets it to `bin\x64\Debug`.

While the starter template indicate `dotnet chromelycef.dll download v65 --cpu=x64 --dest="bin\Debug\netcoreapp2.1"` 

so exute

`dotnet chromelycef.dll download v65 --cpu=x64 --dest="`**`bin\x64\Debug\netcoreapp2.1`**`"` 

or add to the csproj file

`<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">`
`    <OutputPath>`**`bin\Debug\`**`</OutputPath>`
`</PropertyGroup>`
